---
title: "MKollontai_Exercise1"
author: "Misha Kollontai"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise HSE.C25

Solve the given homogenous linear system. 

$$x_{1}+2x_{2}+3x_{3}=0$$
$$2x_{1}-x_{2}+x_{3}=0$$
$$3x_{1}+x_{2}+x_{3}=0$$
$$x_{2}+2x_{3}=0$$

```{r}
UppTri <- function(x,y){
  Aug_base <- cbind(x,y)
  levels <- c(0,0,0)
  Aug <- Aug_base
  
  for(i in c(1:3)){
    if (Aug[i,1] != 0){levels[i] <- 1}
    else {if(Aug[i,2] != 0){levels[i] <- 2}
       else{levels[i] <- 3}
    }
  }

## Start by sorting the rows in order of present variables
   if(levels[1] > levels[2]){
     if(levels[2] < levels[3]){
       Aug[1,] <- Aug_base[2,]
       Aug[2,] <- Aug_base[1,]
       Aug[3,] <- Aug_base[3,]
     } else{
       if(levels[3] <= levels[2]){
          Aug[1,] <- Aug_base[3,]
          Aug[2,] <- Aug_base[2,]
          Aug[3,] <- Aug_base[1,]
       } else{
          Aug[1,] <- Aug_base[2,]
          Aug[2,] <- Aug_base[3,]
          Aug[3,] <- Aug_base[1,]
       }
     }
   } else{
     if(levels[3] > levels[1]){
        Aug[1,] <- Aug_base[1,]
        Aug[2,] <- Aug_base[3,]
        Aug[3,] <- Aug_base[2,]
     } else{
       if(levels[3] < levels[2]){
          Aug[1,] <- Aug_base[3,]
          Aug[2,] <- Aug_base[1,]
          Aug[3,] <- Aug_base[2,]
       }
     }
   }
  
  #Set the first term to 1
  if(Aug[1,1] != 0){
    Aug[1,] <- Aug[1,]/Aug[1,1]
  }
  
  #Ensure that the other two rows have zero values in the first column
  Aug[2,] <- Aug[2,] - Aug[1,]*Aug[2,1]/Aug[1,1]
  Aug[3,] <- Aug[3,] - Aug[1,]*Aug[3,1]/Aug[1,1]
  
  #Set the first value in the second row equal to 1
  if(Aug[2,2] != 0){
    Aug[2,] <- Aug[2,]/Aug[2,2]
    #Zero the value in the third row below the 1 of the second
    Aug[3,] <- Aug[3,] - Aug[2,]*Aug[3,2]/Aug[2,2]
    #If possible, do the same to the first row
    if(Aug[1,2] != 0){
      Aug[1,] <- Aug[1,] - Aug[2,]*Aug[1,2]/Aug[2,2]
    }
  }
  
  if(Aug[3,3] != 0){
    Aug[3,] <- Aug[3,]/Aug[3,3]
    if(Aug[1,3] != 0){
      Aug[1,] <- Aug[1,] - Aug[3,]*Aug[1,3]/Aug[3,3]
    }
    if(Aug[2,3] != 0){
      Aug[2,] <- Aug[2,] - Aug[3,]*Aug[2,3]/Aug[3,3]
    }
  }
  fail <- FALSE
  for(i in c(2,3)){
    if(Aug[i,1] == 0 & Aug[i,2] == 0 & Aug[i,3] ==0 && Aug[i,4] != 0){
      fail <- TRUE
    }
  }
  
  if (fail){
    print("There is no solution")
  }else{
    print("The solution to the system of equations using my function is:")
    print(Aug[,4])
  }
  return(Aug[,4])
}
A <- c(1,2,3,0,2,-1,1,1,3,1,1,2)
dim(A) <- c(4,3)
A
b <- c(0,0,0,0)

Result<- UppTri(A,b)
```